# Generated by Django 6.0.7 on 2026-07-19 20:01

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('user_streak', models.IntegerField(default=0)),
                ('last_activity', models.DateTimeField(default=api.models.get_ist_now)),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('sr_no', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('solution_note', models.TextField(help_text='at max 3 lines')),
                ('topic', models.CharField(max_length=150)),
                ('subtopic', models.CharField(max_length=150)),
                ('date', models.DateTimeField(default=api.models.get_ist_now)),
                ('remark', models.TextField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
