# Generated by Django 6.0.7 on 2026-07-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_questions', models.IntegerField()),
                ('difficulty', models.CharField()),
                ('topic', models.CharField(max_length=150)),
                ('subtopic', models.CharField(max_length=150)),
            ],
        ),
    ]
