# Generated by Django 6.0.7 on 2026-08-30 21:30

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_statistics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('ques_no', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('question_containt', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Content')),
                ('constraints', models.CharField(blank=True, max_length=500)),
                ('hint_1', models.TextField(blank=True)),
                ('hint_2', models.TextField(blank=True)),
                ('hint_3', models.TextField(blank=True)),
                ('topic', models.CharField(max_length=150)),
            ],
        ),
    ]
