# Generated by Django 6.0.7 on 2026-09-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='memoryLimit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='timeLimit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
