# Generated by Django 6.0.7 on 2026-09-02 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_question_memorylimit_question_timelimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='memoryLimit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='timeLimit',
            field=models.FloatField(),
        ),
    ]
