# Generated by Django 6.0.7 on 2026-09-02 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_question_memorylimit_alter_question_timelimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='stdin',
            field=models.CharField(blank=True),
        ),
    ]
