# Generated by Django 6.0.7 on 2026-09-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_question_stdin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='stdin',
            field=models.TextField(blank=True),
        ),
    ]
