# Generated by Django 6.0.7 on 2026-09-22 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_question_stdin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submitted_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('source_code', models.TextField()),
                ('stdin', models.TextField()),
                ('stdout', models.TextField()),
                ('memeory', models.CharField(max_length=50)),
                ('cpu_time', models.CharField(max_length=50)),
                ('question_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
