# Generated by Django 6.0.7 on 2026-09-22 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_submitted_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitted_question',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfo'),
        ),
    ]
