# Generated by Django 6.0.7 on 2026-09-23 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_submitted_question_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submitted_question',
            old_name='memeory',
            new_name='memory',
        ),
    ]
