# Generated by Django 6.0.7 on 2026-09-23 14:59

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_activity',
            field=models.DateTimeField(blank=True, default=api.models.get_ist_now, null=True),
        ),
    ]
